mydata <- read.csv("Documents/zaatari_data/R/zaatariDatasetOriginalLabel.csv", header=TRUE,nrows = 234,na.strings=c(""))
install.packages("ggplot2")
install.packages("GGally")
install.packages("ICC")
install.packages("gdata")
install.packages("plsRglm")
install.packages("randomForest")
install.packages("rpart")
install.packages("regsubsets")
install.packages("leaps")
library(ggplot2)
library(MASS)
library(GGally)
library(ICC)
library(e1071)
library(gam)
library(glmnet)
library(boot)
library(gdata)
library(pls)
library(plsRglm)
library(randomForest)
library(rpart)
library(leaps)

###Presenting Dataset
summary(mydata)
names(mydata)
youth <- mydata[which(mydata$X1_AGE>14&mydata$X1_AGE<26),]
adult <- mydata[which(mydata$X1_AGE>25),]
dim(youth)
dim(adult)
ggpairs(youth[,c("X1_AGE","X2_EDU","X1_SEX")])

###Bivariate Analysis
internetSyriaYouth<-youth[,"X5_INTERNET_SYRIA"]
internetSyriaAdult<-adult[,"X5_INTERNET_SYRIA"]

ggplot(mydata,aes(X5_INTERNET_SYRIA))+ 
  geom_histogram(data=youth,fill="red",alpha=0.2,position="dodge")+
  geom_histogram(data=adult,fill="green",alpha=0.2,position="dodge")

ggplot(mydata,aes(X5_INTERNET_JORDAN))+ 
  geom_histogram(data=youth,fill="red",alpha=0.2,position="dodge")+
  geom_histogram(data=adult,fill="green",alpha=0.2,position="dodge")

###Multivariate Analysis
lda.fit=lda(X5_INTERNET_JORDAN~X5_INTERNET_SYRIA+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata)
lda.fit
coef(lda.fit)
ggpairs(youth[,c("X1_AGE","X1_SEX","X2_EDU","X3_ENGLISH","X5_INTERNET_SYRIA","X5_INTERNET_JORDAN")])
chisq.test(mydata$X1_AGE,mydata$X5_INTERNET_SYRIA)
chisq.test(mydata$X1_AGE,mydata$X5_INTERNET_JORDAN)
chisq.test(mydata$X1_SEX,mydata$X5_INTERNET_SYRIA)
chisq.test(mydata$X1_SEX,mydata$X5_INTERNET_JORDAN)
chisq.test(mydata$X2_EDU,mydata$X5_INTERNET_SYRIA)
chisq.test(mydata$X2_EDU,mydata$X5_INTERNET_JORDAN)
chisq.test(mydata$X3_ENGLISH,mydata$X5_INTERNET_SYRIA)
chisq.test(mydata$X3_ENGLISH,mydata$X5_INTERNET_JORDAN)


###who owns handset
#logistic regression
ownHandset.glm=glm(X13_HANDSET_OWNERSHIP~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata)
ownHandset.glm
summary(ownHandset.glm)

#linear discriminant regression
ownHandset.lda=lda(X13_HANDSET_OWNERSHIP~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata)
ownHandset.lda
summary(ownHandset.lda)
anova(ownHandset.glm,ownHandset.lda,test="F")

dim(mydata[!is.na(mydata$X13_HANDSET_OWNERSHIP),])
set.seed(1)
train=sample(230,150)
ownHandset.glm=glm(X13_HANDSET_OWNERSHIP~Group+X1_AGE+X1_SEX+X2_EDU,data=mydata[!is.na(mydata$X13_HANDSET_OWNERSHIP),],family=binomial,subset=train)
handsetData=mydata[!is.na(mydata$X13_HANDSET_OWNERSHIP),]
drop.levels(handsetData)
ownHandset.glm.probs=predict(ownHandset.glm,handsetData[(-train),],type="response")
ownHandset.glm.pred=rep("No",80)
ownHandset.glm.pred[ownHandset.glm.probs>.5]="Yes"
table(ownHandset.glm.pred,handsetData[-train,"X13_HANDSET_OWNERSHIP"])
#predication accuracy of GLM model on handset ownership is 80%.

###SIM cards ownership
simNumber.glm=glm(X14_SIM_OWN_NUMBER~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata)
simNumber.lda=lda(X14_SIM_BORROW_NUMBER~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata)
simNumber.glm
simNumber.lda
summary(simNumber.glm)
anova(simNumber.glm,simNumber.lda,test="F")

ownMoreSim=ifelse(mydata$X14_SIM_OWN_NUMBER<2,"No","Yes")
ownSim=data.frame(mydata,ownMoreSim)
ownSimData=ownSim[!is.na(mydata$X14_SIM_OWN_NUMBER),]
ownSim.glm=glm(ownMoreSim~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=ownSimData,family=binomial)
ownSim.glm
summary(ownSim.glm)
dim(ownSimData)

#simNumber.gam=gam(X14_SIM_OWN_NUMBER~s(X1_AGE,5)+X2_EDU+X3_ENGLISH+X1_SEX,data=mydata)
#par(mfrow=c(1,3))
#plot.gam(simNumber.gam,se=TRUE,col="blue")
#anova(simNumber.glm,simNumber.gam,test="F")

set.seed(1)
train=sample(198,120)
ownSim.glm=glm(ownMoreSim~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=ownSimData,family=binomial,subset=train)
ownSim.glm.probs=predict(ownSim.glm,ownSimData[-train,],type="response")
ownSim.glm.pred=rep("No",78)
ownSim.glm.pred[ownSim.glm.probs>.5]="Yes"
table(ownSim.glm.pred,ownSimData[-train,"ownMoreSim"])

###SIM card borrow (no significant variables)
borrowMoreSim=ifelse(mydata$X14_SIM_BORROW_NUMBER<2,"No","Yes")
borrowSim=data.frame(mydata,borrowMoreSim)
borrowSimData=borrowSim[!is.na(mydata$X14_SIM_BORROW_NUMBER),]
borrowSim.glm=glm(borrowMoreSim~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=borrowSimData,family=binomial)
borrowSim.glm
summary(borrowSim.glm)
dim(borrowSimData)

borrowSim.lda=lda(borrowMoreSim~Group+X1_AGE+X1_SEX+X2_EDU,data=borrowSimData)
borrowSim.lda
summary(borrowSim.lda)
anova(borrowSim.glm,borrowSim.lda,test="F")

set.seed(1)
train=sample(184,120)
borrowSim.glm=glm(borrowMoreSim~Group+X1_AGE+X1_SEX+X2_EDU,data=borrowSimData,family=binomial,subset=train)
borrowSim.glm.probs=predict(borrowSim.glm,borrowSimData[-train,],type="response")
borrowSim.glm.pred=rep("No",64)
borrowSim.glm.pred[borrowSim.glm.probs>.5]="Yes"
table(borrowSim.glm.pred,borrowSimData[-train,"borrowMoreSim"])


###recieving help
helpReceive.glm=glm(X23_ASSISTANCE_RECEIVE_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata[!is.na(mydata$X23_ASSISTANCE_RECEIVE_YESORNO),],family=binomial)
helpReceive.glm
summary(helpReceive.glm)

helpReceive.lda=lda(X23_ASSISTANCE_RECEIVE_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU,data=mydata[!is.na(mydata$X23_ASSISTANCE_RECEIVE_YESORNO),])
helpReceive.lda
summary(helpReceive.lda)
anova(helpReceive.glm,helpReceive.lda,test="F")

dim(mydata[!is.na(mydata$X23_ASSISTANCE_RECEIVE_YESORNO),])
set.seed(1)
train=sample(221,151)
helpReceive.glm=glm(X23_ASSISTANCE_RECEIVE_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU,data=mydata[!is.na(mydata$X23_ASSISTANCE_RECEIVE_YESORNO),],family=binomial,subset=train)
helpReceiveData=mydata[!is.na(mydata$X23_ASSISTANCE_RECEIVE_YESORNO),]
helpReceive.glm.probs=predict(helpReceive.glm,helpReceiveData[(-train),],type="response")
helpReceive.glm.pred=rep("No",70)
helpReceive.glm.pred[helpReceive.glm.probs>.5]="Yes"
table(helpReceive.glm.pred,helpReceiveData[-train,"X23_ASSISTANCE_RECEIVE_YESORNO"])
#predication accuracy of GLM model is 53%.


###offering help
helpOffer.glm=glm(X24_ASSISTANCE_OFFER_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata[!is.na(mydata$X24_ASSISTANCE_OFFER_YESORNO),],family=binomial)
helpOffer.glm
summary(helpOffer.glm)

helpOffer.lda=lda(X24_ASSISTANCE_OFFER_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH,data=mydata[!is.na(mydata$X24_ASSISTANCE_OFFER_YESORNO),])
helpOffer.lda
summary(helpOffer.lda)
anova(helpOffer.glm,helpOffer.lda,test="F")

dim(mydata[!is.na(mydata$X24_ASSISTANCE_OFFER_YESORNO),])
set.seed(1)
train=sample(208,148)
helpOffer.glm=glm(X24_ASSISTANCE_OFFER_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU,data=mydata[!is.na(mydata$X24_ASSISTANCE_OFFER_YESORNO),],family=binomial,subset=train)
helpOfferData=mydata[!is.na(mydata$X24_ASSISTANCE_OFFER_YESORNO),]
#drop.levels(helpReceiveData)
helpOffer.glm.probs=predict(helpOffer.glm,helpOfferData[(-train),],type="response")
helpOffer.glm.pred=rep("No",60)
helpOffer.glm.pred[helpOffer.glm.probs>.5]="Yes"
table(helpOffer.glm.pred,helpOfferData[-train,"X24_ASSISTANCE_OFFER_YESORNO"])
#predication accuracy of GLM model is 65%.


### forward stepwide selection for social media use in Jordan
socialMedia.fwd=regsubsets(X6_SOCIAL_MEDIA_JORDAN~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH+X5_INTERNET_SYRIA+X5_INTERNET_JORDAN+X6_SOCIAL_MEDIA_SYRIA+#8
                             X7_WATCH_VIDEOS_JORDAN+X8_INFO_SRC_SYRIA+X8_INFO_FREQ_SYRIA+X8_INFO_FREQ_JORDAN+X9_INTERNET_HOW_SYRIA_MYMOBILE_TRUEORFALSE+#5
                             X9_INTERNET_HOW_SYRIA_ELSEPHONE_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+#2
                             X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOWIFINETWORK_TRUEORFALSE+#2
                             X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOWIFI_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_HOW_SYRIA+X10_INTERNET_LOCATION_SYRIA_HOME_TUREORFALSE+#3
                             X10_INTERNET_LOCATION_SYRIA_SCHOOL_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_INTERNETCAFE_TRUEORFALSE+#2
                             X10_INTERNET_LOCATION_SYRIA_FRIENDSHOUSE_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_FAMILY_TRUEORFALSE+#2
                             X10_INTERNET_LOCATION_SYRIA_OTHER_TRUEORFALSE+X10_INTERNET_HOW_JORDAN_IDONTKNOW_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_WHERE_SYRIA+#3
                             X11_INTERNET_HOW_JORDAN_MYPHONE_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSEPHONE_TRUEORFALSE+#2
                             X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+#2
                             X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOWIFI_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOWIFI_TRUEORFALSE+#2
                             X11_INTERNET_HOW_JORDAN_IDONTKNOW+MULTIPLE_CHOICE_INTERNET_HOW_JORDAN+X12_INFO_SRC_JORDAN+#3
                             X12_INFO_SRC_JORDAN_FQC+X13_HANDSET_OWNERSHIP+X13_HANDSET_MODEL+X13_HANDSET_SIM_NUMBER+X14_SIM_OWN_NUMBER+#5
                             X14_SIM_BORROW_NUMBER+X16_COMM_APP_FREQ_SYRIA_COUNT_MOBILEVOICE+X16_COMM_APP_FREQ_SYRIA_COUNT_SMS+#3
                             X16_COMM_APP_FREQ_SYRIA_COUNT_WHATSAPP+X16_COMM_APP_FREQ_SYRIA_COUNT_VIBER+X16_COMM_APP_FREQ_SYRIA_COUNT_SKYPE+#3
                             X16_COMM_APP_FREQ_SYRIA_COUNT_EMAIL+X17_MOBILE_CHOICE_SYRIA+X18_COMM_APP_FREQ_JORDAN_COUNT_MOBILEVOICE+#3
                             X18_COMM_APP_FREQ_JORDAN_COUNT_SMS+X18_COMM_APP_FREQ_JORDAN_COUNT_WHATSAPP+X18_COMM_APP_FREQ_JORDAN_COUNT_VIBER,#3
                             X18_COMM_APP_FREQ_JORDAN_COUNT_SKYPE+X18_COMM_APP_FREQ_JORDAN_COUNT_EMAIL+X19_MOBILE_SERV_CHOICE_JORDAN+X20_DISTRICT_CALL_SYRIA+#4
                             X21_DISTRICT_CALL_JORDAN+X22_ONLINE_ACTIVITY_INTEREST_COUNT_ONLINEEDU+X22_ONLINE_ACTIVITY_INTEREST_COUNT_ONLINETRAINING+#3
                             X22_ONLINE_ACTIVITY_INTEREST_COUNT_INFORSEARCH+X22_ONLINE_ACTIVITY_INTEREST_COUNT_NEWS+X22_ONLINE_ACTIVITY_INTEREST_COUNT_JOBS+
                             X22_ONLINE_ACTIVITY_INTEREST_COUNT_MAPPING+X22_ONLINE_ACTIVITY_INTEREST_COUNT_CONNECTPEOPLEINSIDECAMP+
                             X22_ONLINE_ACTIVITY_INTEREST_COUNT_CONNECTPEOPLEOUTSIDECAMP+X22_ONLINE_ACTIVITY_INTEREST_COUNT_EMAIL+
                             X22_ONLINE_ACTIVITY_INTEREST_COUNT_SKYPE+X22_ONLINE_ACTIVITY_INTEREST_COUNT_VIBER+X22_ONLINE_ACTIVITY_INTEREST_COUNT_WHATSAPP+
                             X22_ONLINE_ACTIVITY_INTEREST_COUNT_TWITTER+X22_ONLINE_ACTIVITY_INTEREST_COUNT_FACEBOOK+X22_ONLINE_ACTIVITY_INTEREST_COUNT_YOUTUBE+
                             X22_ONLINE_ACTIVITY_INTEREST_COUNT_GAMING+X22_ONLINE_ACTIVITY_INTEREST_COUNT_ENTERTAINMENT+X23_ASSISTANCE_RECEIVE_YESORNO+
                             X23_ASSISTANCE_RECEIVE_COUNT_ONLINEEDU+X23_ASSISTANCE_RECEIVE_COUNT_ONLINETRAINING+X23_ASSISTANCE_RECEIVE_COUNT_INFOSEARCH+
                             X23_ASSISTANCE_RECEIVE_COUNT_NEWS+X23_ASSISTANCE_RECEIVE_COUNT_JOBS+X23_ASSISTANCE_RECEIVE_INTEREST_COUNT_MAPPING+
                             X23_ASSISTANCE_RECEIVE_COUNT_CONNECTPEOPLEINSIDEMAP+X23_ASSISTANCE_RECEIVE_COUNT_CONNECTPEOPLEOUTSIDECAMP+
                             X23_ASSISTANCE_RECEIVE_COUNT_EMAIL+X23_ASSISTANCE_RECEIVE_COUNT_SKYPE+X23_ASSISTANCE_RECEIVE_COUNT_VIBER+
                             X23_ASSISTANCE_RECEIVE_COUNT_WHATSAPP+X23_ASSISTANCE_RECEIVE_COUNT_TWITTER+X23_ASSISTANCE_RECEIVE_COUNT_FACEBOOK+
                             X23_ASSISTANCE_RECEIVE_COUNT_YOUTUBE+X23_ASSISTANCE_RECEIVE_COUNT_GAMING+X23_ASSISTANCE_RECEIVE_COUNT_ENTERTAINMENT+
                             X24_ASSISTANCE_OFFER_YESORNO+X24_ASSISTANCE_OFFER_WHO_FAMILY_TRUEORFALSE+X24_ASSISTANCE_OFFER_WHO_FRIENDS_TRUEORFALSE+
                             X24_ASSISTANCE_OFFER_WHO_CAMPSTAFF_TRUEORFALSE+X24_ASSISTANCE_OFFER_WHO_CAMPVISITOR_TRUEORFALSE+
                             X24_ASSISTANCE_OFFER_WHO_OTHERSINSIDECAMP_TRUEORFALSE+X24_ASSISTANCE_OFFER_WHO_OTHERSOUTSIDECAMP_TRUEORFALSE+
                             X24_ASSISTANCE_OFFER_WHO_OTHERS_TRUEORFALSE+X24_ASSISTANCE_OFFER_COUNT_ONLINEEDU+X24_ASSISTANCE_OFFER_COUNT_ONLINETRAINING+
                             X24_ASSISTANCE_OFFER_COUNT_INFOSEARCH+X24_ASSISTANCE_OFFER_COUNT_NEWS+X24_ASSISTANCE_OFFER_COUNT_JOBS+X24_ASSISTANCE_OFFER_COUNT_MAPPING+
                             X24_ASSISTANCE_OFFER_COUNT_CONNECTPEOPLEINSIDECAMP+X24_ASSISTANCE_OFFER_COUNT_CONNECTPEOPLEOUTSIDECAMP+X24_ASSISTANCE_OFFER_COUNT_EMAIL+
                             X24_ASSISTANCE_OFFER_COUNT_SKYPE+X24_ASSISTANCE_OFFER_COUNT_VIBER+X24_ASSISTANCE_OFFER_COUNT_WHATSAPP+X24_ASSISTANCE_OFFER_COUNT_TWITTER+
                             X24_ASSISTANCE_OFFER_COUNT_FACEBOOK+X24_ASSISTANCE_OFFER_COUNT_YOUTUBE+X24_ASSISTANCE_OFFER_COUNT_GAMING+
                             X24_ASSISTANCE_OFFER_COUNT_ENTERTAINMENT+FINISH_TRUEORFALSE,
                           data=mydata,nvmax=140,method="forward")
summary(socialMedia.fwd)
coef(socialMedia.fwd,5)

socialMedia.fwd=regsubsets(X6_SOCIAL_MEDIA_JORDAN~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH+X5_INTERNET_SYRIA+X5_INTERNET_JORDAN+#8
                             X7_WATCH_VIDEOS_JORDAN+X8_INFO_SRC_SYRIA+X8_INFO_FREQ_SYRIA+X8_INFO_FREQ_JORDAN+X9_INTERNET_HOW_SYRIA_MYMOBILE_TRUEORFALSE+#5
                             X9_INTERNET_HOW_SYRIA_ELSEPHONE_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+#2
                             X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOWIFINETWORK_TRUEORFALSE+#2
                             X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOWIFI_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_HOW_SYRIA+X10_INTERNET_LOCATION_SYRIA_HOME_TUREORFALSE+#3
                             X10_INTERNET_LOCATION_SYRIA_SCHOOL_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_INTERNETCAFE_TRUEORFALSE+#2
                             X10_INTERNET_LOCATION_SYRIA_FRIENDSHOUSE_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_FAMILY_TRUEORFALSE+#2
                             X10_INTERNET_LOCATION_SYRIA_OTHER_TRUEORFALSE+X10_INTERNET_HOW_JORDAN_IDONTKNOW_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_WHERE_SYRIA+#3
                             X11_INTERNET_HOW_JORDAN_MYPHONE_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSEPHONE_TRUEORFALSE,#2,
                             data=mydata,nvmax=29,method="forward")

#### forward stepwise selection for help offer
helpOffer.fwd=regsubsets(X24_ASSISTANCE_OFFER_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH+X5_INTERNET_SYRIA+X5_INTERNET_JORDAN+X6_SOCIAL_MEDIA_SYRIA+X6_SOCIAL_MEDIA_JORDAN+#9
                             X7_WATCH_VIDEOS_JORDAN+X8_INFO_SRC_SYRIA+X8_INFO_FREQ_SYRIA+X8_INFO_FREQ_JORDAN+X9_INTERNET_HOW_SYRIA_MYMOBILE_TRUEORFALSE+#5
                             X9_INTERNET_HOW_SYRIA_ELSEPHONE_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+#2
                             X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOWIFINETWORK_TRUEORFALSE+#2
                             X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOWIFI_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_HOW_SYRIA+X10_INTERNET_LOCATION_SYRIA_HOME_TUREORFALSE+#3
                             X10_INTERNET_LOCATION_SYRIA_SCHOOL_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_INTERNETCAFE_TRUEORFALSE+#2
                             X10_INTERNET_LOCATION_SYRIA_FRIENDSHOUSE_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_FAMILY_TRUEORFALSE+#2
                             X10_INTERNET_LOCATION_SYRIA_OTHER_TRUEORFALSE+X10_INTERNET_HOW_JORDAN_IDONTKNOW_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_WHERE_SYRIA+#3
                            X11_INTERNET_HOW_JORDAN_MYPHONE_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSEPHONE_TRUEORFALSE+#2
                             X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+#2
                             X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOWIFI_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOWIFI_TRUEORFALSE,#2
                             X11_INTERNET_HOW_JORDAN_IDONTKNOW+MULTIPLE_CHOICE_INTERNET_HOW_JORDAN+X12_INFO_SRC_JORDAN,#3
                                X12_INFO_SRC_JORDAN_FQC+X13_HANDSET_OWNERSHIP+X13_HANDSET_MODEL+X13_HANDSET_SIM_NUMBER+X14_SIM_OWN_NUMBER,#5
                             X14_SIM_BORROW_NUMBER+X16_COMM_APP_FREQ_SYRIA_COUNT_MOBILEVOICE+X16_COMM_APP_FREQ_SYRIA_COUNT_SMS+#3
                             X16_COMM_APP_FREQ_SYRIA_COUNT_WHATSAPP+X16_COMM_APP_FREQ_SYRIA_COUNT_VIBER+X16_COMM_APP_FREQ_SYRIA_COUNT_SKYPE,
                             X16_COMM_APP_FREQ_SYRIA_COUNT_EMAIL+X17_MOBILE_CHOICE_SYRIA+X18_COMM_APP_FREQ_JORDAN_COUNT_MOBILEVOICE,
                             X18_COMM_APP_FREQ_JORDAN_COUNT_SMS+X18_COMM_APP_FREQ_JORDAN_COUNT_WHATSAPP+X18_COMM_APP_FREQ_JORDAN_COUNT_VIBER+
                            X18_COMM_APP_FREQ_JORDAN_COUNT_SKYPE+X18_COMM_APP_FREQ_JORDAN_COUNT_EMAIL+X19_MOBILE_SERV_CHOICE_JORDAN+X20_DISTRICT_CALL_SYRIA,
                             #X21_DISTRICT_CALL_JORDAN+X22_ONLINE_ACTIVITY_INTEREST_COUNT_ONLINEEDU+X22_ONLINE_ACTIVITY_INTEREST_COUNT_ONLINETRAINING+#3
                             #X22_ONLINE_ACTIVITY_INTEREST_COUNT_INFORSEARCH+X22_ONLINE_ACTIVITY_INTEREST_COUNT_NEWS+X22_ONLINE_ACTIVITY_INTEREST_COUNT_JOBS+
                             #X22_ONLINE_ACTIVITY_INTEREST_COUNT_MAPPING+X22_ONLINE_ACTIVITY_INTEREST_COUNT_CONNECTPEOPLEINSIDECAMP+
                             #X22_ONLINE_ACTIVITY_INTEREST_COUNT_CONNECTPEOPLEOUTSIDECAMP+X22_ONLINE_ACTIVITY_INTEREST_COUNT_EMAIL+
                             #X22_ONLINE_ACTIVITY_INTEREST_COUNT_SKYPE+X22_ONLINE_ACTIVITY_INTEREST_COUNT_VIBER+X22_ONLINE_ACTIVITY_INTEREST_COUNT_WHATSAPP+
                             #X22_ONLINE_ACTIVITY_INTEREST_COUNT_TWITTER+X22_ONLINE_ACTIVITY_INTEREST_COUNT_FACEBOOK+X22_ONLINE_ACTIVITY_INTEREST_COUNT_YOUTUBE+
                             #X22_ONLINE_ACTIVITY_INTEREST_COUNT_GAMING+X22_ONLINE_ACTIVITY_INTEREST_COUNT_ENTERTAINMENT,
                           data=mydata,nvmax=138,method="forward")
helpOffer.fwd
coef(helpOffer.fwd,5)

#### forward stepwise selection for help receive
helpReceive.fwd=regsubsets(X23_ASSISTANCE_RECEIVE_YESORNO~Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH+X5_INTERNET_SYRIA+X5_INTERNET_JORDAN+X6_SOCIAL_MEDIA_SYRIA+X6_SOCIAL_MEDIA_JORDAN+#9
                           X7_WATCH_VIDEOS_JORDAN+X8_INFO_SRC_SYRIA+X8_INFO_FREQ_SYRIA+X8_INFO_FREQ_JORDAN+X9_INTERNET_HOW_SYRIA_MYMOBILE_TRUEORFALSE+#5
                           X9_INTERNET_HOW_SYRIA_ELSEPHONE_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+#2
                           X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOWIFINETWORK_TRUEORFALSE+#2
                           X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOWIFI_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_HOW_SYRIA+X10_INTERNET_LOCATION_SYRIA_HOME_TUREORFALSE+#3
                           X10_INTERNET_LOCATION_SYRIA_SCHOOL_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_INTERNETCAFE_TRUEORFALSE+#2
                           X10_INTERNET_LOCATION_SYRIA_FRIENDSHOUSE_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_FAMILY_TRUEORFALSE+#2
                           X10_INTERNET_LOCATION_SYRIA_OTHER_TRUEORFALSE+X10_INTERNET_HOW_JORDAN_IDONTKNOW_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_WHERE_SYRIA+#3
                           X11_INTERNET_HOW_JORDAN_MYPHONE_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSEPHONE_TRUEORFALSE+#2
                           X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+#2
                           X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOWIFI_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOWIFI_TRUEORFALSE,#2
                         data=mydata,nvmax=138,method="forward")
helpReceive.fwd
coef(helpReceive.fwd,1)
coef(helpReceive.fwd,2)
coef(helpReceive.fwd,3)
coef(helpReceive.fwd,4)
coef(helpReceive.fwd,5)

### feature grouping 
set.seed(1)
train=sample(c(TRUE,FALSE),nrow(mydata),rep=TRUE)
test=(!train)
helpOffer.plsRglm=plsRglm(X24_ASSISTANCE_OFFER_YESORNO, Group+X1_AGE+X1_SEX+X2_EDU+X3_ENGLISH+X5_INTERNET_SYRIA+X5_INTERNET_JORDAN+X6_SOCIAL_MEDIA_SYRIA+
                       X7_WATCH_VIDEOS_JORDAN+X8_INFO_SRC_SYRIA+X8_INFO_FREQ_SYRIA+X8_INFO_FREQ_JORDAN+X9_INTERNET_HOW_SYRIA_MYMOBILE_TRUEORFALSE+
                       X9_INTERNET_HOW_SYRIA_ELSEPHONE_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+
                       X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+X9_INTERNET_HOW_SYRIA_MYCOMPUTERTOWIFINETWORK_TRUEORFALSE+
                       X9_INTERNET_HOW_SYRIA_ELSECOMPUTERTOWIFI_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_HOW_SYRIA+X10_INTERNET_LOCATION_SYRIA_HOME_TUREORFALSE+
                       X10_INTERNET_LOCATION_SYRIA_SCHOOL_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_INTERNETCAFE_TRUEORFALSE+
                       X10_INTERNET_LOCATION_SYRIA_FRIENDSHOUSE_TRUEORFALSE+X10_INTERNET_LOCATION_SYRIA_FAMILY_TRUEORFALSE+
                       X10_INTERNET_LOCATION_SYRIA_OTHER_TRUEORFALSE+X10_INTERNET_HOW_JORDAN_IDONTKNOW_TRUEORFALSE+MULTIPLE_CHOICE_INTERNET_WHERE_SYRIA+
                       X11_INTERNET_HOW_JORDAN_MYPHONE_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSEPHONE_TRUEORFALSE+
                       X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOMOBILENETWORK_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOMOBILENETWORK_TRUEORFALSE+
                       X11_INTERNET_HOW_JORDAN_MYCOMPUTERTOWIFI_TRUEORFALSE+X11_INTERNET_HOW_JORDAN_ELSECOMPUTERTOWIFI_TRUEORFALSE+
                       X11_INTERNET_HOW_JORDAN_IDONTKNOW+MULTIPLE_CHOICE_INTERNET_HOW_JORDAN+X12_INFO_SRC_JORDAN+
                       X12_INFO_SRC_JORDAN_FQC+X13_HANDSET_OWNERSHIP+X13_HANDSET_MODEL+X13_HANDSET_SIM_NUMBER+X14_SIM_OWN_NUMBER+
                       X14_SIM_BORROW_NUMBER+X16_COMM_APP_FREQ_SYRIA_COUNT_MOBILEVOICE+X16_COMM_APP_FREQ_SYRIA_COUNT_SMS+
                       X16_COMM_APP_FREQ_SYRIA_COUNT_WHATSAPP+X16_COMM_APP_FREQ_SYRIA_COUNT_VIBER+X16_COMM_APP_FREQ_SYRIA_COUNT_SKYPE+
                       X16_COMM_APP_FREQ_SYRIA_COUNT_EMAIL+X17_MOBILE_CHOICE_SYRIA+X18_COMM_APP_FREQ_JORDAN_COUNT_MOBILEVOICE+
                       X18_COMM_APP_FREQ_JORDAN_COUNT_SMS+X18_COMM_APP_FREQ_JORDAN_COUNT_WHATSAPP+X18_COMM_APP_FREQ_JORDAN_COUNT_VIBER,
                     data=mydata,subset=train,scale=TRUE,validation="CV",modele="pls-glm-logistic")







